---
- name: mysql镜像文件分发
  copy: src={{item}} dest={{tmp_dir}}
  with_fileglob:
  - "{{software_dir}}/doom-mysql.tar.gz"

- name: 加载doom-mysql镜像
  shell: docker load < {{ tmp_dir }}/doom-mysql.tar.gz

- name: 启动doom-mysql
  shell: docker run -itd --name {{ mysql_name }}  -p 3306:3306 -e MYSQL_ROOT_PASSWORD={{ mysql_password }} {{ mysql_image }} && sleep 10
  ignore_errors: True

- name: 创建doom数据库
  shell: docker exec -it {{ mysql_name }} sh -c 'exec mysql -uroot -p123456 -B -e "create database doom;"'

  