---
- name: 创建临时目录
  file: name={{tmp_dir}} state=directory

- name: mysql镜像文件分发
  copy: src={{item}} dest={{tmp_dir}}
  with_fileglob:
  - "{{software_dir}}/doom-mysql.tar.gz"

- name: 加载doom-mysql镜像
  shell: docker load < {{ tmp_dir }}/doom-mysql.tar.gz

- name: 判断doom-mysql是否在运行
  shell: docker ps -a | awk 'NR != 1{print $NF}' | grep {{mysql_name}}
  register: mysqlName
  ignore_errors: True
- debug: var=mysqlName

- name: 删除doom-mysql
  shell: docker rm -f {{ mysql_name }}
  when: mysqlName.stdout == mysql_name

- name: 启动doom-mysql
  block:
    - name: 启动doom-mysql
      shell: docker run -itd --name {{ mysql_name }} -v /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime -p 3306:3306 -e MYSQL_ROOT_PASSWORD={{ mysql_password }} {{ mysql_image }} --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  rescue:
    - name: 失败重启doom-mysql
      shell: docker restart {{ mysql_name }}
    

- name: 创建doom数据库
  block:
    - name: 休息10s尝试创建数据库
      shell: sleep 10 && docker exec -it {{ mysql_name }} sh -c 'exec mysql -uroot -p{{ mysql_password }} -e "{{doom_init_sql}}" '
  rescue:
    - name: 休息10s再次尝试创建数据库
      shell: sleep 10 && docker exec -it {{ mysql_name }} sh -c 'exec mysql -uroot -p{{ mysql_password }} -e "{{doom_init_sql}}"'


  
