---
- name: 创建临时目录
  file: name={{tmp_dir}} state=directory

- name: 分发doom-server二进制包
  copy: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "{{ software_dir }}/doom-server.tar.gz"

- name: 载入镜像
  shell: docker load < {{ tmp_dir }}/doom-server.tar.gz

- name: 删除doom-server
  shell: docker rm -f {{ doom_name }}
  ignore_errors: True

- name: 启动doom server
  shell: docker run -d --name {{ doom_name }} -p 80:80 -p 8000:8000 -p 7001:7001 {{ doom_image }}

- name: 渲染配置文件
  template: src=pocdoom.properties.j2 dest={{ tmp_dir }}/pocdoom.properties
 

- name: 复制配置文件到容器中
  shell: docker cp {{ tmp_dir }}/pocdoom.properties {{ doom_name }}:/home/admin/pocdoom.properties

- name: 重启doom-server
  shell: docker restart {{ doom_name }}

- name: 分发客户端包
  copy: src={{item}} dest={{ tmp_dir }}
  with_fileglob:
  - "{{ software_dir }}/{{client_pkg}}"

- name: 上传客户端包到doom-server
  shell: docker cp  {{ tmp_dir }}/{{client_pkg}} {{doom_name}}:/home/admin/doom/client_library/

