---
- name: 判断docker是否已安装
  shell: "docker --version &> /dev/null; echo $?"
  register: is_docker_existed

- debug: var=is_docker_existed

- name: 创建临时目录
  file: name={{tmp_dir}} state=directory
  when: is_docker_existed.stdout != "0"

- name: 分发并解压docker二进制包
  unarchive: src={{ item }} dest={{ tmp_dir }}
  with_fileglob:
    - "{{ software_dir }}/docker-*.tgz"
  when: is_docker_existed.stdout != "0"

- name: 移动docker二进制文件
  shell: cp -rf {{ tmp_dir }}/docker/* /usr/bin
  when: is_docker_existed.stdout != "0"

- name: 分发service文件
  copy: src=docker.service dest=/usr/lib/systemd/system/
  when: is_docker_existed.stdout != "0"

- name: 启动docker
  systemd: name=docker state=restarted enabled=yes daemon_reload=yes

- name: 查看状态
  shell: docker info
  register: docker 
- debug: var=docker.stdout_lines
