---
- name: 创建临时目录
  file: name={{tmp_dir}} state=directory

- name: 分发镜像
  copy: src={{item}} dest={{ tmp_dir }}
  with_fileglob:
  - "{{software_dir}}/doom-redis.tar.gz"

- name: 加载redis 镜像
  shell: docker image load < {{ tmp_dir }}/doom-redis.tar.gz

- name: 删除redis容器
  shell: docker rm -f {{ redis_name }}
  ignore_errors: True

- name: 启动redis
  block:
  - name: 尝试启动doom-redis
    shell: docker run -itd --name {{ redis_name }} -p {{ redis_port }}:6379  {{ redis_image }}
  rescue:
  - name: 失败重启doom-redis
    shell: docker restart {{ redis_name }}